# Generated by Django 6.0.4 on 2026-08-28 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancejob',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.mechanic'),
        ),
        migrations.AlterField(
            model_name='maintenancejob',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicle'),
        ),
    ]
